name = "nexus"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "nexus-db"
database_id = "to-be-filled-after-creation"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "nexus-assets"
